# Playbook: Zabbix Deploy. 
#
#
- name: Deploy zabbix mysql
  hosts: zabbix_mysql
  max_fail_percentage: 0
  roles:
    - { role: "zabbix-mysql" }

- name: Deploy Zabbix Server
  hosts: zabbix_servers 
  max_fail_percentage: 0 
  roles:
    - { role: "zabbix-server" }

- name: Deploy Zabbix Agent
  hosts: zabbix_agents 
  max_fail_percentage: 0 
  roles:
    - { role: "zabbix-agent" }

